version: '3.9'

services:
  db:
    image: postgres:16
    container_name: car_rental_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: car_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
